UPDATE APPLICATION_CONFIGURATION
SET VALUE=0 
WHERE KEY=' activemq.queue.prefetch.size '; 
UPDATE APPLICATION_CONFIGURATION SET VALUE=150
WHERE KEY=' activemq.connectionfactory.size '; 
COMMIT; 

UPDATE E_PROC_LOCK_HDR 
SET PROCESS_TYPE='FREQUENCY',MIN=1,BATCH_GROUP=MISC
WHERE PROC_NAME LIKE '%ReflectiveReprocessBatch%'
AND WHSE='US1'; 
UPDATE E_PROC_LOCK_HDR SET MIN=1,THREAD_POOL=20
WHERE PROC_NAME='ReprocessCICOProcessor'
AND WHSE='US1'; UPDATE E_PROC_LOCK_HDR 
SET MIN=1 
WHERE PROC_NAME='TSNSReprocessBatch' 
AND PROCESS_TYPE='FREQUENCY' 
AND WHSE='US1'; 
UPDATE E_PROC_LOCK_HDR 
SET BATCH_GROUP='GROUP1' 
WHERE PROC_NAME='PerfEvalutionProcessBatch' 
AND WHSE='US1';
UPDATE E_PROC_LOCK_HDR SET THREAD_POOL=20 
WHERE PROC_NAME='RuleEngine' 
AND PROCESS_TYPE='FREQUENCY' 
AND WHSE='US1'; UPDATE E_PROC_LOCK_HDR 
SET PARAMETERS='reprocessDays=7' 
WHERE PROC_NAME='RuleEngine' AND PROCESS_TYPE='SCHEDULE' AND WHSE='US1'; 
COMMIT; 
 
