BEGIN
DBMS_SCHEDULER.DISABLE('CL_MESSAGE_PURGE_JOB');
DBMS_SCHEDULER.DISABLE('EVENT_MESSAGE_PURGE_JOB');
DBMS_SCHEDULER.DISABLE('LRF_SCHED_EVENT_RPT_PURGE_JOB');
DBMS_SCHEDULER.DISABLE('OM_SCHED_EVENT_PURGE_JOB');
END;
